---  
- hosts: all
  become: true
  
  tasks:    
    - name: Pull image from dockerhub
      command: docker pull akila1811/spe-mini-project:latest
    
    - name: Building docker container from image
      command: docker run -d --name calci akila1811/spe-mini-project:latest
