---
- name: Pull docker image of Calculator
  hosts: all
  become: yes
  become_method: sudo
  become_user: akila  
  
    
  tasks:   
    - name: Install docker
      apt:
        name: 'docker-ce'
        state: present
        force_apt_get: "yes"
        
    - name: Start docker service
      service:
        name: 'docker'
        state: started
        enabled: yes
        
    - name: Pull image
      docker_image:
        name: akila1811/spe-mini-project
        source: pull
    
