---
- name: Pull docker image of Calculator
  hosts: all
  become: yes
  become_method: sudo
  become_user: akila  
  
    
  tasks:   
    - name: Start services
      service: 
        name: 'yum install docker'
        state: started
        enabled: yes
        
    - name: Pull image
      docker_image:
        name: akila1811/spe-mini-project
        source: pull
    
