---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start services
      service: 
        name: docker 
        state: started
        
    - name: Pull image
      docker_image:
        name: akila1811/spe-mini-project
        source: pull
    
