---
- name: Pull docker image of Calculator
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  become_ask_pass: False
  tasks:
    - name: install docker
      yum: name=docker
      
    - name: Start services
      service: 
        name: docker 
        state: started
        
    - name: Pull image
      docker_image:
        name: akila1811/spe-mini-project
        source: pull
    
